apiVersion: apps/v1
kind: Deployment
metadata:
  name: gist-api-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gist-api-java
  template:
    metadata:
      labels:
        app: gist-api-java
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: gist-api-java
        image: REPLACE_WITH_IMAGE
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
